POST http://localhost:8000/users/
Content-Type: application/json

{
    "username": "faith",
    "password":"fai254",
    "email": "fay@gmail.com"
}

###
GET http://localhost:8000/users/
Content-Type: application/json

###
PUT http://localhost:8000/users/9dc70d7e-18af-4372-bca0-d00f0fd7559c
Content-Type:  application/json

{
    "username": "marto",
    "password":"ndegzmarto",
    "email": "ndegz@gmail.com"
}


###
DELETE http://localhost:8000/users/9dc70d7e-18af-4372-bca0-d00f0fd7559c
Content-Type:  application/json


### 
POST  http://localhost:8000/signup/
Content-Type: application/json

{
    "username": "faith267",
    "password": "stargirl",
    "email": "faith254@gmail.com"
}